MVCProyecto/Web/Controllers/CategoriaActivoController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Web.Security;
using Web.Utils;

namespace Web.Controllers
{
    public class CategoriaActivoController : Controller
    {
        // GET: CategoriaActivo
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Index()
        {
            try
            {
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                // Pasar el Error a la página que lo muestra
                TempData["Message"] = ex.Message;
                TempData.Keep();
                return RedirectToAction("Default", "Error");
            }
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult List()
        {
            IEnumerable<CategoriaActivo> lista = null;
            try
            {
                Log.Info("Visita");


                IServiceCategoriaActivo _ServiceCategoriaActivo = new ServiceCategoriaActivo();
                lista = _ServiceCategoriaActivo.GetCategoriaActivo();
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());

                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

            return View(lista);
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Save(CategoriaActivo categoriaActivo)
        {
            string errores = "";
            try
            {
                // Es valido
                if (ModelState.IsValid)
                {
                    ServiceCategoriaActivo _ServiceCategoriaActivo = new ServiceCategoriaActivo();
                    _ServiceCategoriaActivo.Save(categoriaActivo);
                    TempData["Action"] = "S";
                }
                else
                {
                    // Valida Errores si Javascript está deshabilitado
                    Util.ValidateErrors(this);

                    TempData["Message"] = "Error al procesar los datos! " + errores;
                    TempData["Action"] = "E";
                    TempData.Keep();

                    return View("Create", categoriaActivo);
                }

                // redirigir
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Details(int? id)
        {
            ServiceCategoriaActivo _ServiceCategoriaActivo = new ServiceCategoriaActivo();
            CategoriaActivo categoriaActivo = null;

            try
            {
                // Si va null
                if (id == null)
                {
                    return RedirectToAction("List");
                }

                categoriaActivo = _ServiceCategoriaActivo.GetCategoriaActivoByID(id.Value);

                return View(categoriaActivo);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Edit(int? id)
        {
            IServiceCategoriaActivo _ServiceCategoriaActivo = new ServiceCategoriaActivo();
            CategoriaActivo categoriaActivo = null;
            try
            {
                // Si va null
                if (id == null)
                {
                    return RedirectToAction("List");
                }

                categoriaActivo = _ServiceCategoriaActivo.GetCategoriaActivoByID(id.Value);
                TempData["Action"] = "U";
                // Response.StatusCode = 500;
                return View(categoriaActivo);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Delete(int? id)
        {
            try
            {
                // Si va null
                if (id == null)
                {
                    return RedirectToAction("List");
                }

                ServiceCategoriaActivo _ServiceCategoriaActivo = new ServiceCategoriaActivo();
                CategoriaActivo categoriaActivo = _ServiceCategoriaActivo.GetCategoriaActivoByID(id.Value);

                return View(categoriaActivo);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult DeleteConfirmed(int? id)
        {
            ServiceCategoriaActivo _ServiceCategoriaActivo = new ServiceCategoriaActivo();

            try
            {

                if (id == null)
                {
                    return View();
                }

                _ServiceCategoriaActivo.DeleteCategoriaActivo(id.Value);
                TempData["Action"] = "D";

                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }







    }
}

MVCProyecto/Web/Views/CategoriaActivo/Create.cshtml
@model Infraestructure.Models.CategoriaActivo

@{
    ViewBag.Title = "Categoria del Activo";
}

<h2>Crear Nueva Categoria</h2>


@using (Html.BeginForm("Save", "CategoriaActivo", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdCategoriaActivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdCategoriaActivo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdCategoriaActivo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success btn-block" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "btn btn-primary btn-lg" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCProyecto/Web/Views/CategoriaActivo/Delete.cshtml
@model Infraestructure.Models.CategoriaActivo

@{
    ViewBag.Title = "Categoria de Activo";
}

<h2>Eliminar Categoria del Activo</h2>

<h3>Seguro que quiere eliminar esto?</h3>
<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdCategoriaActivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdCategoriaActivo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "CategoriaActivo", new { @id = Model.IdCategoriaActivo}, FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger btn-lg" /> 
            @Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "btn btn-primary btn-lg" })
        </div>
    }
</div>

MVCProyecto/Web/Views/CategoriaActivo/Details.cshtml
@model Infraestructure.Models.CategoriaActivo

@{
    ViewBag.Title = "Categoria de Activo";
}

<h2>Detalles de Categoria</h2>

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdCategoriaActivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdCategoriaActivo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdCategoriaActivo }, new { @class = "btn  btn-primary btn-lg" }) 
    @Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "btn btn-primary btn-lg" })
</p>

MVCProyecto/Web/Views/CategoriaActivo/Edit.cshtml
@model Infraestructure.Models.CategoriaActivo

@{
    ViewBag.Title = "Categoria del Activo";
}

<h2>Editar Categoria del Activo</h2>


@using (Html.BeginForm("Save","CategoriaActivo",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdCategoriaActivo)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success btn-block" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "btn btn-primary btn-lg" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCProyecto/Web/Views/CategoriaActivo/List.cshtml
@model IEnumerable<Infraestructure.Models.CategoriaActivo>

@{
    ViewBag.Title = "Categoria de Activo";
}

<h2>Lista de Categorias del Activo</h2>
@if (TempData["Message"] != null)
{
    string mensaje = @"<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'>
<span aria-hidden='true'>&times;</span> </button><strong>Error!</strong> " + TempData["Message"] + " </div>";
@Html.Raw(mensaje);
}
<p>
    @Html.ActionLink("Nuevo", "Create", null, new { @class = "btn btn-info btn-md" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.IdCategoriaActivo }, new { @class = "btn  btn-primary btn-md " })
                @Html.ActionLink("Detalles", "Details", new { id = item.IdCategoriaActivo }, new { @class = "btn btn-warning btn-md " })
                @Html.ActionLink("Eliminar", "Delete", new { id = item.IdCategoriaActivo }, new { @class = "btn  btn-danger  btn-md " })
            </td>
        </tr>
    }

</table>
@section Scripts {
    @Scripts.Render("~/bundles/toastjs")
    <script>
    $(document).ready(function () {
    console.log("Entro a JQuery")

    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": true,
        "positionClass": "toast-bottom-right",
        "preventDuplicates": true,
        "onclick": null,
        "showDuration": "400",
        "hideDuration": "1200",
        "timeOut": "5500",
        "extendedTimeOut": "1200",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }

    // Recibe los parámetros del Controller
    var option = '@TempData["Action"]'
    var message = '@TempData["Mensaje"]'


    if (option == 'S') {
    toastr.success("La Categoria fue salvado correctamente");
    }


    if (option == 'D') {
        toastr.warning("La Categoria fue borrado correctamente");
    }


    if (option == 'U') {
        toastr.info("La Categoria fue actualizado correctamente");
    }

    if (option == 'E') {
            toastr.error("Se ha producido un error :" + message);
    }


    // Cambiar el color del fondo del Grid.
    $(".table tbody tr:even").css("background-color", "#ddd");
    });



    </script>

}