MVCProyecto/Web/Controllers/MarcaController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Security;
using Web.Utils;

namespace Web.Controllers
{
    public class MarcaController : Controller
    {
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        // GET: Marca
        public ActionResult Index()
        {
            try
            {
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                // Pasar el Error a la página que lo muestra
                TempData["Message"] = ex.Message;
                TempData.Keep();
                return RedirectToAction("Default", "Error");
            }
        }


        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        // GET: Marca/Create
        public ActionResult Create()
        {
            return View();
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult List()
        {
            IEnumerable<Marca> lista = null;
            try
            {
                Log.Info("Visita");


                IServiceMarca _ServiceMarca = new ServiceMarca();
                lista = _ServiceMarca.GetMarca();
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());

                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

            return View(lista);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Save(Marca marca)
        {
            string errores = "";
            try
            {
                // Es valido
                if (ModelState.IsValid)
                {
                    ServiceMarca _ServiceMarca = new ServiceMarca();
                    _ServiceMarca.Save(marca);
                    TempData["Action"] = "S";
                }
                else
                {
                    // Valida Errores si Javascript está deshabilitado
                    Util.ValidateErrors(this);

                    TempData["Message"] = "Error al procesar los datos! " + errores;
                    TempData["Action"] = "E";
                    TempData.Keep();

                    return View("Create", marca);
                }

                // redirigir
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Details(int? id)
        {
            ServiceMarca _ServiceCategoriaActivo = new ServiceMarca();
            Marca marca = null;

            try
            {
                // Si va null
                if (id == null)
                {
                    return RedirectToAction("List");
                }

                marca = _ServiceCategoriaActivo.GetMarcaByID(id.Value);

                return View(marca);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Edit(int? id)
        {
            IServiceMarca _ServiceMarca = new ServiceMarca();
            Marca marca = null;
            try
            {
                // Si va null
                if (id == null)
                {
                    return RedirectToAction("List");
                }

                marca = _ServiceMarca.GetMarcaByID(id.Value);
                TempData["Action"] = "U";
                // Response.StatusCode = 500;
                return View(marca);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Delete(int? id)
        {
            try
            {
                // Si va null
                if (id == null)
                {
                    return RedirectToAction("List");
                }

                ServiceMarca _ServiceMarca = new ServiceMarca();
                Marca marca = _ServiceMarca.GetMarcaByID(id.Value);

                return View(marca);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult DeleteConfirmed(int? id)
        {
            ServiceMarca _ServiceMarca = new ServiceMarca();

            try
            {

                if (id == null)
                {
                    return View();
                }

                _ServiceMarca.DeleteMarca(id.Value);
                TempData["Action"] = "D";

                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
        // GetProductoByName
        [CustomAuthorize((int)Roles.Administrador,(int)Roles.Procesos)]
        public ActionResult GetMarcaByName(string name)
        {
            try
            {
                IServiceMarca _ServiceMarca = new ServiceMarca();
                var lista = _ServiceMarca.GetMarcaByName(name).ToList();

                // Configurar Serialización
                var settings = new JsonSerializerSettings()
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                    Error = (sender, args) =>
                    {
                        args.ErrorContext.Handled = true;
                    },
                };


                string json = JsonConvert.SerializeObject(lista, settings);

                return Content(json);
            }
            catch (Exception err)
            {
                ViewBag.Message = err.Message;
                return View();
            }
        }

    }
}

MVCProyecto/Web/Views/Marca/Create.cshtml
@model Infraestructure.Models.Marca

@{
    ViewBag.Title = "Create";
}

<h2>Crear Marca</h2>


@using (Html.BeginForm("Save","Marca",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdMarca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdMarca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdMarca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success btn-block" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "btn btn-primary btn-lg" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCProyecto/Web/Views/Marca/Delete.cshtml
@model Infraestructure.Models.Marca

@{
    ViewBag.Title = "Marca";
}

<h2>Eliminar Marca</h2>

<h3>Seguro que quiere eliminar esto?</h3>
<div>
    <h4>Marca</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdMarca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdMarca)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "Marca", new { @id = Model.IdMarca }, FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger btn-lg" /> 
            @Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "btn btn-primary btn-lg" })
        </div>
    }
</div>

MVCProyecto/Web/Views/Marca/Details.cshtml
@model Infraestructure.Models.Marca

@{
    ViewBag.Title = "Marca";
}

<h2>Detalles de Marca</h2>

<div>
    <h4>Marca</h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.IdMarca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdMarca)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdMarca }, new { @class = "btn btn-primary btn-lg" }) 
    @Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "btn btn-primary btn-lg" })
</p>

MVCProyecto/Web/Views/Marca/Edit.cshtml
@model Infraestructure.Models.Marca

@{
    ViewBag.Title = "Marca";
}

<h2>Editar Marca</h2>


@using (Html.BeginForm("Save","Marca",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdMarca)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success btn-block" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "btn btn-primary btn-lg" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCProyecto/Web/Views/Marca/List.cshtml
@model IEnumerable<Infraestructure.Models.Marca>

@{
    ViewBag.Title = "Marca";
}

<h2>Lista de Marcas</h2>
@if (TempData["Message"] != null)
{
    string mensaje = @"<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'>
<span aria-hidden='true'>&times;</span> </button><strong>Error!</strong> " + TempData["Message"] + " </div>";
@Html.Raw(mensaje);
}
<p>
    @Html.ActionLink("Nuevo", "Create", null, new { @class = "btn btn-info btn-md" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.IdMarca }, new { @class = "btn  btn-primary btn-md " })
                @Html.ActionLink("Detalles", "Details", new { id = item.IdMarca }, new { @class = "btn btn-warning btn-md " })
                @Html.ActionLink("Eliminar", "Delete", new { id = item.IdMarca }, new { @class = "btn  btn-danger  btn-md " })
            </td>
        </tr>
    }

</table>
@section Scripts {
    @Scripts.Render("~/bundles/toastjs")
    <script>
    $(document).ready(function () {
    console.log("Entro a JQuery")

    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": true,
        "positionClass": "toast-bottom-right",
        "preventDuplicates": true,
        "onclick": null,
        "showDuration": "400",
        "hideDuration": "1200",
        "timeOut": "5500",
        "extendedTimeOut": "1200",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }

    // Recibe los parámetros del Controller
    var option = '@TempData["Action"]'
    var message = '@TempData["Mensaje"]'


    if (option == 'S') {
    toastr.success("La Marca fue salvado correctamente");
    }


    if (option == 'D') {
        toastr.warning("La Marca fue borrado correctamente");
    }


    if (option == 'U') {
        toastr.info("La Marca fue actualizado correctamente");
    }

    if (option == 'E') {
            toastr.error("Se ha producido un error :" + message);
    }


    // Cambiar el color del fondo del Grid.
    $(".table tbody tr:even").css("background-color", "#ddd");
    });



    </script>

}