MVCProyecto/Web/Controllers/DepreciacionController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Security;
using Web.ViewModels;

namespace Web.Controllers
{
    public class DepreciacionController : Controller
    {
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        // GET: Depreciacion
        public ActionResult MainDepreciacion()
        {
            return View();
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult AjaxDepreciacion(ViewModelDepreciacion depreciacion)
        {
            IServiceHistoricoDepreciacion _ServiceHistoricoDeoreciacion = new ServiceHistoricoDepreciacion();
            List<HistoricoDepreciacion> lista = _ServiceHistoricoDeoreciacion.Save(depreciacion.FechaDepreciacion);
            if (lista == null )
            {
                TempData["Message"] = "No puede depreciar meses anteriores a la fecha actual";
                TempData.Keep();
                return PartialView("ActionError");
               
            }
            else
            {
                if (lista.Count() == 0)
                {
                    TempData["Message"] = "No puede depreciar dos veces en el mismo mes";
                    TempData.Keep();
                    return PartialView("ActionError");
                }
                else
                {
                    return PartialView("_DetalleDepreciacion", lista);
                }       
                
            }
           



        }
    }
}

MVCProyecto/Web/Controllers/ReporteController.cs
using Infraestructure.Models;
using iText.Kernel.Pdf;
using Newtonsoft.Json;
using System;
using iText.IO.Font.Constants;
using iText.IO.Image;
using iText.Kernel.Colors;
using iText.Kernel.Font;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using iText.Svg.Converter;
using System.Web.Mvc;
using System.Collections.Generic;
using ApplicationCore.Services;
using System.IO;
using System.Linq;
using System.Reflection;
using Web.Security;
using Web.ViewModels;

namespace Web.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos,(int)Roles.Reportes)]
        public ActionResult Index()
        {
            try
            {

                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                // Pasar el Error a la página que lo muestra
                TempData["Message"] = ex.Message;
                TempData.Keep();
                return RedirectToAction("Default", "Error");
            }
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos, (int)Roles.Reportes)]
        public ActionResult List()
        {
            IEnumerable<Activo> lista = null;
            try
            {
                Log.Info("Visita");


                IServiceActivo _ServiceActivo = new ServiceActivo();
                lista = _ServiceActivo.GetActivo();


            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());

                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

            return View(lista);
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos, (int)Roles.Reportes)]
        public ActionResult CreatePdfActivo()
        {
            IEnumerable<Activo> lista = null;
            try
            {
                // Extraer informacion
                IServiceActivo service = new ServiceActivo();
                lista = service.GetActivo();

                // Crear stream para almacenar en memoria el reporte 
                MemoryStream ms = new MemoryStream();
                //Initialize writer
                PdfWriter writer = new PdfWriter(ms);

                //Inicia el document
                PdfDocument pdfDoc = new PdfDocument(writer);
                Document doc = new Document(pdfDoc);
                // Crea el header / Encabezado
                Paragraph header = new Paragraph("Catalogo de Activos")
                                   .SetFont(PdfFontFactory.CreateFont(StandardFonts.HELVETICA))
                                   .SetFontSize(14)
                                   .SetFontColor(ColorConstants.BLUE);
                // Agrega el Encabezado
                doc.Add(header);


                // Crear tabla con 4 columnas 
                Table table = new Table(5, true);

                // los Encabezados
                table.AddHeaderCell("Código");
                table.AddHeaderCell("Descripción");
                table.AddHeaderCell("Costo");
                table.AddHeaderCell("Marca");
                table.AddHeaderCell("Imagen");
                int cont = 0;
                // Recorre la lista
                foreach (var item in lista)
                {

                    // Agregar datos a las celdas
                    table.AddCell(new Paragraph(item.IdActivo.ToString()));
                    table.AddCell(new Paragraph(item.Descripcion.ToString()));
                    table.AddCell(new Paragraph(item.ValorActual.ToString("C2")));
                    table.AddCell(new Paragraph(item.Marca.Descripcion.ToString()));
                    // Convierte la imagen que viene en Bytes en imagen para PDF
                    Image image = new Image(ImageDataFactory.Create(item.imgActivo));
                    // Tamaño de la imagen
                    image = image.SetHeight(75).SetWidth(75);
                    table.AddCell(image);
                    cont++;


                }
                // Agrega la tabla al documento pdf
                doc.Add(table);

                Paragraph cant = new Paragraph("Cantidad de Activos: "+cont.ToString())
                                   .SetFont(PdfFontFactory.CreateFont(StandardFonts.HELVETICA))
                                   .SetFontSize(10)
                                   .SetFontColor(ColorConstants.BLACK);
                doc.Add(cant);
                // Colocar número de páginas
                int numberOfPages = pdfDoc.GetNumberOfPages();
                for (int i = 1; i <= numberOfPages; i++)
                {

                    // Write aligned text to the specified by parameters point
                    doc.ShowTextAligned(new Paragraph(String.Format("pag {0} of {1}", i, numberOfPages)),
                            559, 826, i, TextAlignment.RIGHT, VerticalAlignment.TOP, 0);

                }


                //Close document
                doc.Close();

                // Retorna un File
                return File(ms.ToArray(), "application/pdf", "Catalogo de Activos");

            }
            catch (Exception ex)
            {
                Exception temp = ex;
                return null;
            }

        }
        public ActionResult FilterActivoByID()
        {
            IServiceActivo _ServiceActivo = new ServiceActivo();
            ViewBag.ListaActivo = _ServiceActivo.GetActivo();
            return View();
        }
        public ActionResult AjaxFilterActivoByID(ViewModelParametro parametro)
        {
            IServiceActivo _ServiceActivo = new ServiceActivo();
            Activo activo = _ServiceActivo.GetActivoByID(parametro.IdActivo);
            
            return PartialView("_DetalleActivo",activo);
        }
        //Vista Reporte Rango garantía
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos, (int)Roles.Reportes)]
        public ActionResult IndexGarantia()
        {
            try
            {
                return View();

            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

        }
        //Partial View Rango Garantía
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos, (int)Roles.Reportes)]
        public ActionResult AjaxVencimientoGarantiaRango(ViewModelGarantia garantia)
        {
            try
            {
                IServiceActivo _ServiceActivo = new ServiceActivo();
                List<Activo> lista = _ServiceActivo.GetActivoByVencimientoGarantia(garantia.IniGarantia, garantia.FinGarantia);
                return PartialView("_DetalleGarantia", lista);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

        }
    }
}

MVCProyecto/Web/Controllers/UsuarioController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Security;
using Web.Utils;

namespace Web.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        [CustomAuthorize((int)Roles.Administrador)]
        public ActionResult Index()
        {
            try
            {
               
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                // Pasar el Error a la página que lo muestra
                TempData["Message"] = ex.Message;
                TempData.Keep();
                return RedirectToAction("Default", "Error");
            }
        }
        [CustomAuthorize((int)Roles.Administrador)]
        public ActionResult List()
        {
            IEnumerable<Usuario> lista = null;
            try
            {
                
                Log.Info("Visita");


                IServiceUsuario _ServiceUsuario = new ServiceUsuario();
                lista = _ServiceUsuario.GetUsuario();
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());

                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

            return View(lista);
        }
        // GET: Usuario/Create
         [CustomAuthorize((int)Roles.Administrador)]
        public ActionResult Create()
        {
            IServiceCategoriaUsuario _ServiceCategoriaUsuario = new ServiceCategoriaUsuario();
            ViewBag.ListaCategoriaUsuario = _ServiceCategoriaUsuario.GetCategoriaUsuario();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
         [CustomAuthorize((int)Roles.Administrador)]
        public ActionResult Save(Usuario usuario)
        {
            string errores = "";
            try
            {
                // Es valido
                if (ModelState.IsValid)
                {
                    ServiceUsuario _ServiceUsuario = new ServiceUsuario();

                    _ServiceUsuario.Save(usuario);
                    TempData["Action"] = "S";
                }
                else
                {
                    // Valida Errores si Javascript está deshabilitado
                    Util.ValidateErrors(this);

                    TempData["Message"] = "Error al procesar los datos! " + errores;
                    TempData["Action"] = "E";
                    TempData.Keep();

                    return View("Create", usuario);
                }

                // redirigir
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        [CustomAuthorize((int)Roles.Administrador)]
        public ActionResult Details(int? id)
        {
            ServiceUsuario _ServiceUsuario = new ServiceUsuario();
            Usuario usuario = null;

            try
            {
                // Si va null
                if (id == null)
                {
                    return RedirectToAction("List");
                }

                usuario = _ServiceUsuario.GetUsuarioByID(id.Value.ToString());

                return View(usuario);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
        [CustomAuthorize((int)Roles.Administrador)]
        public ActionResult Edit(int? id)
        {
            IServiceUsuario _ServiceUsuario = new ServiceUsuario();
            Usuario usuario = null;
            try
            {
                // Si va null
                if (id == null)
                {
                    return RedirectToAction("List");
                }
                IServiceCategoriaUsuario _ServiceCategoriaUsuario = new ServiceCategoriaUsuario();
                ViewBag.ListaCategoriaUsuario = _ServiceCategoriaUsuario.GetCategoriaUsuario();

                usuario = _ServiceUsuario.GetUsuarioByID(id.Value.ToString());
                TempData["Action"] = "U";
                // Response.StatusCode = 500;
                return View(usuario);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
        [CustomAuthorize((int)Roles.Administrador)]
        public ActionResult Delete(int? id)
        {
            try
            {
                // Si va null
                if (id == null)
                {
                    return RedirectToAction("List");
                }

                ServiceUsuario _ServiceUsuario = new ServiceUsuario();
                Usuario usuario = _ServiceUsuario.GetUsuarioByID(id.Value.ToString());

                return View(usuario);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
         [CustomAuthorize((int)Roles.Administrador)]
        public ActionResult DeleteConfirmed(int? id)
        {
            ServiceUsuario _ServiceUsuario = new ServiceUsuario();

            try
            {

                if (id == null)
                {
                    return View();
                }

                _ServiceUsuario.DeleteUsuario(id.Value.ToString());
                TempData["Action"] = "D";

                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Action"] = "E";
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

    }
}

MVCProyecto/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/toastr.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Control de Activos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mantenimientos <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Vendedor", "Index", "Vendedor")</li>
                            <li>@Html.ActionLink("Activo Falta", "About", "Home")</li>
                            <li>@Html.ActionLink("Categoria de Activo", "Index", "CategoriaActivo")</li>
                            <li>@Html.ActionLink("Marca", "Index", "Marca")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Procesos <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cálculo Depreciación", "Index", "Home")</li>


                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reportes <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Vendedor", "Index", "Vendedor")</li>
                            <li>@Html.ActionLink("Activo Falta", "About", "Home")</li>
                            <li>@Html.ActionLink("Categoria de Activo", "Index", "CategoriaActivo")</li>
                            <li>@Html.ActionLink("Marca", "Index", "Marca")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administracion <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Seguridad", "Index", "Usuario")</li>
                            

                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCProyecto/Web/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Control de Activos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/toastr.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Control de Activos", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020-Proyecto Programación VI. </p>
            <p> Carlos Lizano</p>
            <p>Version @typeof(Web.MvcApplication).Assembly.GetName().Version.ToString()</p>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCProyecto/Web/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Control de Activos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/toastr.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header ">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Control de Activos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Mantenimiento <span class="glyphicon  glyphicon glyphicon-plus" />
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Vendedor", "Index", "Vendedor")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Activo", "Index", "Activo")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Categoría del Activo", "Index", "CategoriaActivo")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Marca", "Index", "Marca")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Aseguradora", "Index", "Aseguradora")</li>


                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Procesos   <span class="glyphicon  glyphicon-cog" />
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cálculo Depreciación", "MainDepreciacion", "Depreciacion")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Reportes <span class="glyphicon  glyphicon glyphicon-print" />
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Catálogo de Activos (PDF)", "List", "Reporte")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Activo por ID", "FilterActivoByID", "Reporte")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Vencimiento de Fechas Activo", "IndexGarantia", "Reporte")</li>

                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Administración   <span class="glyphicon glyphicon-lock" />
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Seguridad", "Index", "Usuario")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Autoevaluacion", "Evaluacion", "Home")</li>

                </ul>

            
                <ul class="nav navbar-nav ">
                    <li>
                        <a href="@Url.Action("Logout", "Login")">
                            Logout
                            <span class="glyphicon   glyphicon-log-out" aria-hidden="true"></span>
                        </a>

                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @{
                            string nombre = "";
                            Infraestructure.Models.Usuario oUsuario;
                            // Validar si vienen datos en la session
                            if (Session["User"] != null)
                            {
                                // Casting
                                oUsuario = Session["User"] as Infraestructure.Models.Usuario;

                                if (oUsuario != null)
                                {
                                    nombre = $"{oUsuario.Nombre} {oUsuario.Apellidos}";
                                }
                            }


                        }

                        <a href="#">
                             @nombre
                            <span class="glyphicon  glyphicon-user " aria-hidden="true"></span>
                        </a>


                    </li>
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Proyecto Programación VI.  </p>
            <p> Carlos Lizano</p>
            <p>Version @typeof(Web.MvcApplication).Assembly.GetName().Version.ToString()</p>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>